version: "3"

services:
  lili-tracker:
    image: lili-tracker
    build: .
    container_name: lili-tracker
    restart: always
    ports:
      - "16001:80"
    volumes:
      - ./logs:/root/tracker
