version: "3"

services:
  lili-tracker:
    image: darknightlab/lili-tracker:main
    # build: .
    container_name: lili-tracker
    restart: always
    ports:
      - "16001:80"
    command:
      [
        "--http",
        "--ws",
        "-p",
        "80",
        "--trust-proxy",
        "--interval",
        "600000"
      ]
